#!/usr/bin/env node
/**
 * Generates config.js from environment variables at deploy time.
 *
 * Platform setup (Netlify / Vercel / Cloudflare Pages):
 *   Set these env vars in your hosting dashboard:
 *     QA_SHEETS_ENDPOINT   → your Google Apps Script Web App URL
 *     QA_AI_EVAL_ENDPOINT  → your serverless function URL (Claude API key stays there)
 *
 * This script runs as a build command before the site is published.
 * Add to your platform's build command:
 *   node build-config.js
 *
 * For Netlify: Build command = "node build-config.js"
 * For Vercel:  Add to vercel.json buildCommand or package.json scripts
 */

const fs   = require('fs');
const path = require('path');

const sheetsEndpoint  = process.env.QA_SHEETS_ENDPOINT  || '';
const aiEvalEndpoint  = process.env.QA_AI_EVAL_ENDPOINT || '';

if (!sheetsEndpoint)  console.warn('[build-config] WARNING: QA_SHEETS_ENDPOINT is not set');
if (!aiEvalEndpoint)  console.warn('[build-config] WARNING: QA_AI_EVAL_ENDPOINT is not set');

const content = `/* Auto-generated by build-config.js — do not edit manually */
window.QA_CONFIG = {
  sheetsEndpoint: ${JSON.stringify(sheetsEndpoint)},
  aiEvalEndpoint: ${JSON.stringify(aiEvalEndpoint)}
};
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), content, 'utf8');
console.log('[build-config] config.js written successfully');
